query GetChannel($channelId: String!) {
  channel(channelId: $channelId) {
    id
    name
    createdAt
    description
    createdBy {
      id
      name
      username
    }
    members {
      id
      name
      username
      friendStatus
    }
  }
}
