query GetChannelInfoForSidebar($channelId: String!) {
  channel(channelId: $channelId) {
    id
    name
    createdBy {
      id
      name
      username
    }
    createdAt
    members {
      id
      name
      username
      friendStatus
    }
  }
}
