mutation RemoveMembersFromChannel(
  $channelId: String!
  $membersIds: [String!]!
) {
  removeMembersFromChannel(channelId: $channelId, membersIds: $membersIds) {
    id
    members {
      id
    }
  }
}
