subscription Chats {
  chats {
    __typename
    id
    createdBy {
      id
      username
      name
    }
    ... on GroupChat {
      name
      memberCount
    }
    ... on DeletedChat {
      deletedAt
    }
  }
}
