subscription Chats {
  chats {
    __typename
    id
    createdById
    createdBy {
      id
      ...NameParts
    }
    ... on DirectMessageChat {
      friend {
        id
        ...NameParts
      }
    }
    ... on GroupChat {
      members {
        id
        ...NameParts
      }
    }
    ... on DeletedChat {
      deletedAt
    }
  }
}