subscription MeChanged {
  meChanged {
    id
    ...NameParts
    ...ReceivedFriendRequests
    chats {
      name
      id
      description
      members {
        __typename
        ... on Friend {
          id
          ...NameParts
        }
        ... on Stranger {
          id
          ...NameParts
        }
        ... on Me {
          id
          ...NameParts
        }
      }
    }
  }
}
