subscription MeChanged {
  meChanged {
    id
    ...NameParts
    ...ReceivedFriendRequests
    chats {
      name
      id
      description
      members {
        id
        username
      }
    }
  }
}
