subscription Notifications {
  notifications {
    id
    createdAt
    isCreator
    createdBy {
      id
      username
      name
    }
    ... on ChatInvite {
      status
      chat {
        __typename
        ... on GroupChat {
          name
          memberCount
        }
      }
    }
    ... on FriendRequest {
      ...RequestInfo
    }
  }
}
