subscription Notifications {
  notifications {
    id
    createdAt
    createdBy {
      id
      ...NameParts
    }
    ... on ChatInvite {
      status
      chat {
        __typename
        ... on GroupChat {
          name
          memberCount
        }
      }
    }
    ... on FriendRequest {
      status
    }
  }
}
