query GetChannelMessages(
  $channelId: Int!
  $first: Int
  $after: String
  $last: Int
  $before: String
) {
  Channel(id: $channelId) {
    id
    name
    isDM
    messages(first: $first, after: $after, last: $last, before: $before) {
      edges {
        cursor
        node {
          id
          content
          createdAt
          createdById
          createdBy {
            id
            name
            username
          }
          likedBy {
            id
            name
            username
          }
          updatedAt
        }
      }
    }
  }
}
