query GetAdminSelector($chatId: HashId!) {
  chat(chatId: $chatId) {
    __typename
    ... on GroupChat {
      isCreator
      members {
        id
        username
        name
      }
      admins {
        id
        username
        name
      }
    }
  }
  friends {
    id
    username
    name
  }
}
