query GetChat($chatId: String!) {
  chat(chatId: $chatId) {
    id
    name
    createdAt
    description
    createdBy {
      id
      ...NameParts
    }
    members {
      id
      ...NameParts
      friendStatus
    }
  }
}
