query GetChatMessages(
  $chatId: String!
  $last: Int
  $after: String
  $first: Int
  $before: String
) {
  chatMessages(
    chatId: $chatId
    last: $last
    after: $after
    first: $first
    before: $before
  ) {
    pageInfo {
      startCursor
      endCursor
      hasPreviousPage
      hasNextPage
    }
    edges {
      node {
        id
        content
        createdAt
        createdBy {
          __typename
          ... on Stranger {
            id
            ...NameParts
          }
          ... on Me {
            id
          }
          ... on Friend {
            id
            ...NameParts
          }
        }
      }
    }
  }
}
