query GetChats {
  chats {
    __typename
    id
    createdBy {
      id
      username
      name
    }
    isCreator
    ... on DirectMessageChat {
      friend {
        id
        username
        name
      }
    }
    ... on GroupChat {
      name
      description
      members {
        id
        username
        name
      }
    }
  }
}
