query Chats {
  chats {
    ... on DirectMessageChat {
      id
      friend {
        id
        ...NameParts
      }
    }
    ... on GroupChat {
      id
      name
      description
      members {
        __typename
        ... on Friend {
          id
          ...NameParts
        }
        ... on Stranger {
          id
          ...NameParts
        }
        ... on Me {
          id
          ...NameParts
        }
      }
    }
    ... on DeletedChat {
      id
      deletedAt
    }
  }
}
