query GetChat($chatId: HashId!) {
  chat(chatId: $chatId) {
    __typename
    id
    createdBy {
      id
      ...NameParts
    }
    createdAt
    updatedAt
    isCreator
    ... on DirectMessageChat {
      friend {
        id
        ...NameParts
      }
    }
    ... on GroupChat {
      members {
        id
        ...NameParts
      }
      name
      description
    }
  }
}
