query GetChat($chatId: String!) {
  chat(chatId: $chatId) {
    __typename
    ... on DirectMessageChat {
      id
      friend {
        id
        ...NameParts
      }
    }
    ... on GroupChat {
      id
      name
      description
      members {
        __typename
        ... on Stranger {
          id
          ...NameParts
        }
        ... on Me {
          id
        }
        ... on Friend {
          id
          ...NameParts
        }
      }
    }
    ... on DeletedChat {
      id
    }
  }
}
