query GetMessages($chatId: HashId!, $last: Int) {
  messages(chatId: $chatId, first: $last) {
    pageInfo {
      hasPreviousPage
      startCursor
    }
    edges {
      cursor
      node {
        __typename
        id
        isCreator
        createdAt
        createdBy {
          id
          username
          name
        }
        ... on DeletedMessage {
          deletedAt
        }
        ... on InstantMessage {
          content
        }
      }
    }
  }
}
