query GetMessages($chatId: HashId!, $last: Int, $before: String) {
  messages(chatId: $chatId, last: $last, before: $before) {
    pageInfo {
      hasPreviousPage
      startCursor
    }
    edges {
      node {
        ...MessageData
        ... on DeletedMessage {
          deletedAt
        }
        ... on InstantMessage {
          content
        }
      }
    }
  }
}
