query GetMessages($chatId: HashId!, $last: Int, $before: String) {
  messages(chatId: $chatId, last: $last, before: $before) {
    pageInfo {
      hasPreviousPage
      startCursor
    }
    edges {
      node {
        __typename
        id
        isCreator
        createdAt
        createdBy {
          id
          username
          name
        }
        ... on DeletedMessage {
          deletedAt
        }
        ... on InstantMessage {
          content
        }
      }
    }
  }
}
