/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { IContext } from "./graphql/context.interface"
import type { core, connectionPluginCore } from "nexus"
import type { FieldAuthorizeResolver } from "nexus/dist/plugins/fieldAuthorizePlugin"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * Date custom scalar type
     */
    date<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "Date";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * Date custom scalar type
     */
    date<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "Date";
    /**
     * Adds a Relay-style connection to the type, with numerous options for configuration
     *
     * @see https://nexusjs.org/docs/plugins/connection
     */
    connectionField<FieldName extends string>(
      fieldName: FieldName,
      config: connectionPluginCore.ConnectionFieldConfig<TypeName, FieldName>
    ): void
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  CreateGroupChatInput: { // input type
    description?: string | null; // String
    memberIds?: string[] | null; // [ID!]
    name: string; // String!
  }
  UpdateChatInput: { // input type
    addMemberIds?: string[] | null; // [ID!]
    chatId: string; // ID!
    description?: string | null; // String
    name?: string | null; // String
    removeMemberIds?: string[] | null; // [ID!]
  }
  UserOrderBy: { // input type
    createdAt?: NexusGenEnums['Sort'] | null; // Sort
    email?: NexusGenEnums['Sort'] | null; // Sort
    id?: NexusGenEnums['Sort'] | null; // Sort
    name?: NexusGenEnums['Sort'] | null; // Sort
    updatedAt?: NexusGenEnums['Sort'] | null; // Sort
    username?: NexusGenEnums['Sort'] | null; // Sort
  }
}

export interface NexusGenEnums {
  FriendStatus: "FRIEND" | "NOT_FRIEND" | "REQUEST_RECEIVED" | "REQUEST_SENT"
  Sort: "asc" | "desc"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  Date: any
}

export interface NexusGenObjects {
  DeletedChat: { // root type
    chatId: string; // ID!
    createdBy?: NexusGenRootTypes['UserResult'] | null; // UserResult
    createdById: string; // ID!
    deletedAt: NexusGenScalars['Date']; // Date!
    updatedAt?: NexusGenScalars['Date'] | null; // Date
  }
  DeletedMessage: { // root type
    chatId: string; // String!
    createdAt: NexusGenScalars['Date']; // Date!
    createdById: string; // String!
    deletedAt?: NexusGenScalars['Date'] | null; // Date
    messageId: string; // ID!
    updatedAt: NexusGenScalars['Date']; // Date!
  }
  DirectMessageChat: { // root type
    chatId: string; // ID!
    createdBy?: NexusGenRootTypes['UserResult'] | null; // UserResult
    createdById: string; // ID!
    updatedAt?: NexusGenScalars['Date'] | null; // Date
  }
  Friend: { // root type
    createdAt: NexusGenScalars['Date']; // Date!
    name?: string | null; // String
    updatedAt: NexusGenScalars['Date']; // Date!
    userId: string; // ID!
    username: string; // String!
  }
  FriendConnection: { // root type
    edges?: Array<NexusGenRootTypes['FriendEdge'] | null> | null; // [FriendEdge]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  FriendEdge: { // root type
    cursor: string; // String!
    node?: NexusGenRootTypes['Friend'] | null; // Friend
  }
  GroupChat: { // root type
    chatId: string; // ID!
    createdBy?: NexusGenRootTypes['UserResult'] | null; // UserResult
    createdById: string; // ID!
    description?: string | null; // String
    name: string; // String!
    updatedAt?: NexusGenScalars['Date'] | null; // Date
  }
  Me: { // root type
    createdAt: NexusGenScalars['Date']; // Date!
    name?: string | null; // String
    updatedAt: NexusGenScalars['Date']; // Date!
    userId: string; // ID!
    username: string; // String!
  }
  Message: { // root type
    chatId: string; // String!
    content: string; // String!
    createdAt: NexusGenScalars['Date']; // Date!
    createdById: string; // String!
    deletedAt?: NexusGenScalars['Date'] | null; // Date
    messageId: string; // ID!
    updatedAt: NexusGenScalars['Date']; // Date!
  }
  MessageResultConnection: { // root type
    edges?: Array<NexusGenRootTypes['MessageResultEdge'] | null> | null; // [MessageResultEdge]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  MessageResultEdge: { // root type
    cursor: string; // String!
    node?: NexusGenRootTypes['MessageResult'] | null; // MessageResult
  }
  Mutation: {};
  PageInfo: { // root type
    endCursor?: string | null; // String
    hasNextPage: boolean; // Boolean!
    hasPreviousPage: boolean; // Boolean!
    startCursor?: string | null; // String
  }
  Query: {};
  Stranger: { // root type
    createdAt: NexusGenScalars['Date']; // Date!
    name?: string | null; // String
    updatedAt: NexusGenScalars['Date']; // Date!
    userId: string; // ID!
    username: string; // String!
  }
  Subscription: {};
  UserResultConnection: { // root type
    edges?: Array<NexusGenRootTypes['UserResultEdge'] | null> | null; // [UserResultEdge]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  UserResultEdge: { // root type
    cursor: string; // String!
    node?: NexusGenRootTypes['UserResult'] | null; // UserResult
  }
}

export interface NexusGenInterfaces {
  ChatInterface: NexusGenRootTypes['DeletedChat'] | NexusGenRootTypes['DirectMessageChat'] | NexusGenRootTypes['GroupChat'];
  KnownUserInterface: NexusGenRootTypes['Friend'] | NexusGenRootTypes['Me'];
  MessageInterface: NexusGenRootTypes['DeletedMessage'] | NexusGenRootTypes['Message'];
  UserInterface: NexusGenRootTypes['Friend'] | NexusGenRootTypes['Me'] | NexusGenRootTypes['Stranger'];
}

export interface NexusGenUnions {
  ChatResult: NexusGenRootTypes['DeletedChat'] | NexusGenRootTypes['DirectMessageChat'] | NexusGenRootTypes['GroupChat'];
  MessageResult: NexusGenRootTypes['DeletedMessage'] | NexusGenRootTypes['Message'];
  UserResult: NexusGenRootTypes['Friend'] | NexusGenRootTypes['Me'] | NexusGenRootTypes['Stranger'];
}

export type NexusGenRootTypes = NexusGenInterfaces & NexusGenObjects & NexusGenUnions

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  DeletedChat: { // field return type
    chatId: string; // ID!
    createdBy: NexusGenRootTypes['UserResult'] | null; // UserResult
    createdById: string; // ID!
    deletedAt: NexusGenScalars['Date']; // Date!
    isCreator: boolean; // Boolean!
    updatedAt: NexusGenScalars['Date'] | null; // Date
  }
  DeletedMessage: { // field return type
    chat: NexusGenRootTypes['ChatResult']; // ChatResult!
    chatId: string; // String!
    createdAt: NexusGenScalars['Date']; // Date!
    createdBy: NexusGenRootTypes['UserResult']; // UserResult!
    createdById: string; // String!
    deletedAt: NexusGenScalars['Date'] | null; // Date
    isCreator: boolean; // Boolean!
    messageId: string; // ID!
    updatedAt: NexusGenScalars['Date']; // Date!
  }
  DirectMessageChat: { // field return type
    chatId: string; // ID!
    createdBy: NexusGenRootTypes['UserResult'] | null; // UserResult
    createdById: string; // ID!
    friend: NexusGenRootTypes['Friend']; // Friend!
    isCreator: boolean; // Boolean!
    messages: NexusGenRootTypes['MessageResultConnection']; // MessageResultConnection!
    updatedAt: NexusGenScalars['Date'] | null; // Date
  }
  Friend: { // field return type
    chats: NexusGenRootTypes['ChatResult'][]; // [ChatResult!]!
    createdAt: NexusGenScalars['Date']; // Date!
    friendStatus: NexusGenEnums['FriendStatus']; // FriendStatus!
    friends: NexusGenRootTypes['FriendConnection']; // FriendConnection!
    name: string | null; // String
    receivedFriendRequests: NexusGenRootTypes['UserResult'][]; // [UserResult!]!
    updatedAt: NexusGenScalars['Date']; // Date!
    userId: string; // ID!
    username: string; // String!
  }
  FriendConnection: { // field return type
    edges: Array<NexusGenRootTypes['FriendEdge'] | null> | null; // [FriendEdge]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  FriendEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['Friend'] | null; // Friend
  }
  GroupChat: { // field return type
    chatId: string; // ID!
    createdBy: NexusGenRootTypes['UserResult'] | null; // UserResult
    createdById: string; // ID!
    description: string | null; // String
    isCreator: boolean; // Boolean!
    memberCount: number; // Int!
    members: NexusGenRootTypes['UserResult'][]; // [UserResult!]!
    name: string; // String!
    updatedAt: NexusGenScalars['Date'] | null; // Date
  }
  Me: { // field return type
    chats: NexusGenRootTypes['ChatResult'][]; // [ChatResult!]!
    createdAt: NexusGenScalars['Date']; // Date!
    friendStatus: NexusGenEnums['FriendStatus']; // FriendStatus!
    friends: NexusGenRootTypes['FriendConnection']; // FriendConnection!
    name: string | null; // String
    receivedFriendRequests: NexusGenRootTypes['UserResult'][]; // [UserResult!]!
    updatedAt: NexusGenScalars['Date']; // Date!
    userId: string; // ID!
    username: string; // String!
  }
  Message: { // field return type
    chat: NexusGenRootTypes['ChatResult']; // ChatResult!
    chatId: string; // String!
    content: string; // String!
    createdAt: NexusGenScalars['Date']; // Date!
    createdBy: NexusGenRootTypes['UserResult']; // UserResult!
    createdById: string; // String!
    deletedAt: NexusGenScalars['Date'] | null; // Date
    isCreator: boolean; // Boolean!
    likedBy: NexusGenRootTypes['UserResult'][]; // [UserResult!]!
    messageId: string; // ID!
    updatedAt: NexusGenScalars['Date']; // Date!
  }
  MessageResultConnection: { // field return type
    edges: Array<NexusGenRootTypes['MessageResultEdge'] | null> | null; // [MessageResultEdge]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  MessageResultEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['MessageResult'] | null; // MessageResult
  }
  Mutation: { // field return type
    acceptFriendRequest: NexusGenRootTypes['Friend'] | null; // Friend
    addMembersToGroupChat: NexusGenRootTypes['ChatResult'] | null; // ChatResult
    cancelFriendRequest: NexusGenRootTypes['Stranger'] | null; // Stranger
    createDirectMessageChat: NexusGenRootTypes['DirectMessageChat'] | null; // DirectMessageChat
    createGroupChat: NexusGenRootTypes['GroupChat'] | null; // GroupChat
    createMessage: NexusGenRootTypes['Message'] | null; // Message
    declineFriendRequest: NexusGenRootTypes['Stranger'] | null; // Stranger
    deleteChat: NexusGenRootTypes['DeletedChat'] | null; // DeletedChat
    deleteFriend: NexusGenRootTypes['Stranger'] | null; // Stranger
    deleteMessage: NexusGenRootTypes['Message'] | null; // Message
    removeMembersFromChat: NexusGenRootTypes['ChatResult'] | null; // ChatResult
    sendFriendRequest: NexusGenRootTypes['Stranger'] | null; // Stranger
    updateChat: NexusGenRootTypes['ChatResult'] | null; // ChatResult
    updateMe: NexusGenRootTypes['Me'] | null; // Me
    updateMessage: NexusGenRootTypes['Message'] | null; // Message
  }
  PageInfo: { // field return type
    endCursor: string | null; // String
    hasNextPage: boolean; // Boolean!
    hasPreviousPage: boolean; // Boolean!
    startCursor: string | null; // String
  }
  Query: { // field return type
    chat: NexusGenRootTypes['ChatResult'] | null; // ChatResult
    chats: NexusGenRootTypes['ChatResult'][]; // [ChatResult!]!
    friends: NexusGenRootTypes['Friend'][]; // [Friend!]!
    me: NexusGenRootTypes['Me'] | null; // Me
    message: NexusGenRootTypes['MessageResult'] | null; // MessageResult
    messages: NexusGenRootTypes['MessageResultConnection']; // MessageResultConnection!
    user: NexusGenRootTypes['UserResult'] | null; // UserResult
    users: NexusGenRootTypes['UserResultConnection']; // UserResultConnection!
  }
  Stranger: { // field return type
    createdAt: NexusGenScalars['Date']; // Date!
    friendStatus: NexusGenEnums['FriendStatus']; // FriendStatus!
    name: string | null; // String
    updatedAt: NexusGenScalars['Date']; // Date!
    userId: string; // ID!
    username: string; // String!
  }
  Subscription: { // field return type
    chatCreated: NexusGenRootTypes['ChatResult'] | null; // ChatResult
    chatDeleted: NexusGenRootTypes['DeletedChat'] | null; // DeletedChat
    chats: NexusGenRootTypes['ChatResult'] | null; // ChatResult
    messageDeleted: NexusGenRootTypes['Message'] | null; // Message
    messageUpdated: NexusGenRootTypes['MessageResult'] | null; // MessageResult
    messages: NexusGenRootTypes['Message'] | null; // Message
  }
  UserResultConnection: { // field return type
    edges: Array<NexusGenRootTypes['UserResultEdge'] | null> | null; // [UserResultEdge]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  UserResultEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['UserResult'] | null; // UserResult
  }
  ChatInterface: { // field return type
    chatId: string; // ID!
    createdBy: NexusGenRootTypes['UserResult'] | null; // UserResult
    createdById: string; // ID!
    isCreator: boolean; // Boolean!
    updatedAt: NexusGenScalars['Date'] | null; // Date
  }
  KnownUserInterface: { // field return type
    chats: NexusGenRootTypes['ChatResult'][]; // [ChatResult!]!
    friends: NexusGenRootTypes['FriendConnection']; // FriendConnection!
    receivedFriendRequests: NexusGenRootTypes['UserResult'][]; // [UserResult!]!
  }
  MessageInterface: { // field return type
    chat: NexusGenRootTypes['ChatResult']; // ChatResult!
    chatId: string; // String!
    createdAt: NexusGenScalars['Date']; // Date!
    createdBy: NexusGenRootTypes['UserResult']; // UserResult!
    createdById: string; // String!
    deletedAt: NexusGenScalars['Date'] | null; // Date
    isCreator: boolean; // Boolean!
    messageId: string; // ID!
    updatedAt: NexusGenScalars['Date']; // Date!
  }
  UserInterface: { // field return type
    createdAt: NexusGenScalars['Date']; // Date!
    friendStatus: NexusGenEnums['FriendStatus']; // FriendStatus!
    name: string | null; // String
    updatedAt: NexusGenScalars['Date']; // Date!
    userId: string; // ID!
    username: string; // String!
  }
}

export interface NexusGenFieldTypeNames {
  DeletedChat: { // field return type name
    chatId: 'ID'
    createdBy: 'UserResult'
    createdById: 'ID'
    deletedAt: 'Date'
    isCreator: 'Boolean'
    updatedAt: 'Date'
  }
  DeletedMessage: { // field return type name
    chat: 'ChatResult'
    chatId: 'String'
    createdAt: 'Date'
    createdBy: 'UserResult'
    createdById: 'String'
    deletedAt: 'Date'
    isCreator: 'Boolean'
    messageId: 'ID'
    updatedAt: 'Date'
  }
  DirectMessageChat: { // field return type name
    chatId: 'ID'
    createdBy: 'UserResult'
    createdById: 'ID'
    friend: 'Friend'
    isCreator: 'Boolean'
    messages: 'MessageResultConnection'
    updatedAt: 'Date'
  }
  Friend: { // field return type name
    chats: 'ChatResult'
    createdAt: 'Date'
    friendStatus: 'FriendStatus'
    friends: 'FriendConnection'
    name: 'String'
    receivedFriendRequests: 'UserResult'
    updatedAt: 'Date'
    userId: 'ID'
    username: 'String'
  }
  FriendConnection: { // field return type name
    edges: 'FriendEdge'
    pageInfo: 'PageInfo'
  }
  FriendEdge: { // field return type name
    cursor: 'String'
    node: 'Friend'
  }
  GroupChat: { // field return type name
    chatId: 'ID'
    createdBy: 'UserResult'
    createdById: 'ID'
    description: 'String'
    isCreator: 'Boolean'
    memberCount: 'Int'
    members: 'UserResult'
    name: 'String'
    updatedAt: 'Date'
  }
  Me: { // field return type name
    chats: 'ChatResult'
    createdAt: 'Date'
    friendStatus: 'FriendStatus'
    friends: 'FriendConnection'
    name: 'String'
    receivedFriendRequests: 'UserResult'
    updatedAt: 'Date'
    userId: 'ID'
    username: 'String'
  }
  Message: { // field return type name
    chat: 'ChatResult'
    chatId: 'String'
    content: 'String'
    createdAt: 'Date'
    createdBy: 'UserResult'
    createdById: 'String'
    deletedAt: 'Date'
    isCreator: 'Boolean'
    likedBy: 'UserResult'
    messageId: 'ID'
    updatedAt: 'Date'
  }
  MessageResultConnection: { // field return type name
    edges: 'MessageResultEdge'
    pageInfo: 'PageInfo'
  }
  MessageResultEdge: { // field return type name
    cursor: 'String'
    node: 'MessageResult'
  }
  Mutation: { // field return type name
    acceptFriendRequest: 'Friend'
    addMembersToGroupChat: 'ChatResult'
    cancelFriendRequest: 'Stranger'
    createDirectMessageChat: 'DirectMessageChat'
    createGroupChat: 'GroupChat'
    createMessage: 'Message'
    declineFriendRequest: 'Stranger'
    deleteChat: 'DeletedChat'
    deleteFriend: 'Stranger'
    deleteMessage: 'Message'
    removeMembersFromChat: 'ChatResult'
    sendFriendRequest: 'Stranger'
    updateChat: 'ChatResult'
    updateMe: 'Me'
    updateMessage: 'Message'
  }
  PageInfo: { // field return type name
    endCursor: 'String'
    hasNextPage: 'Boolean'
    hasPreviousPage: 'Boolean'
    startCursor: 'String'
  }
  Query: { // field return type name
    chat: 'ChatResult'
    chats: 'ChatResult'
    friends: 'Friend'
    me: 'Me'
    message: 'MessageResult'
    messages: 'MessageResultConnection'
    user: 'UserResult'
    users: 'UserResultConnection'
  }
  Stranger: { // field return type name
    createdAt: 'Date'
    friendStatus: 'FriendStatus'
    name: 'String'
    updatedAt: 'Date'
    userId: 'ID'
    username: 'String'
  }
  Subscription: { // field return type name
    chatCreated: 'ChatResult'
    chatDeleted: 'DeletedChat'
    chats: 'ChatResult'
    messageDeleted: 'Message'
    messageUpdated: 'MessageResult'
    messages: 'Message'
  }
  UserResultConnection: { // field return type name
    edges: 'UserResultEdge'
    pageInfo: 'PageInfo'
  }
  UserResultEdge: { // field return type name
    cursor: 'String'
    node: 'UserResult'
  }
  ChatInterface: { // field return type name
    chatId: 'ID'
    createdBy: 'UserResult'
    createdById: 'ID'
    isCreator: 'Boolean'
    updatedAt: 'Date'
  }
  KnownUserInterface: { // field return type name
    chats: 'ChatResult'
    friends: 'FriendConnection'
    receivedFriendRequests: 'UserResult'
  }
  MessageInterface: { // field return type name
    chat: 'ChatResult'
    chatId: 'String'
    createdAt: 'Date'
    createdBy: 'UserResult'
    createdById: 'String'
    deletedAt: 'Date'
    isCreator: 'Boolean'
    messageId: 'ID'
    updatedAt: 'Date'
  }
  UserInterface: { // field return type name
    createdAt: 'Date'
    friendStatus: 'FriendStatus'
    name: 'String'
    updatedAt: 'Date'
    userId: 'ID'
    username: 'String'
  }
}

export interface NexusGenArgTypes {
  DirectMessageChat: {
    messages: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  Friend: {
    friends: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  Me: {
    friends: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  Mutation: {
    acceptFriendRequest: { // args
      friendId: string; // String!
    }
    addMembersToGroupChat: { // args
      chatId: string; // String!
      memberIds: string[]; // [String!]!
    }
    cancelFriendRequest: { // args
      friendId: string; // String!
    }
    createDirectMessageChat: { // args
      friendId: string; // String!
    }
    createGroupChat: { // args
      data?: NexusGenInputs['CreateGroupChatInput'] | null; // CreateGroupChatInput
    }
    createMessage: { // args
      chatId: string; // String!
      content: string; // String!
    }
    declineFriendRequest: { // args
      friendId: string; // String!
    }
    deleteChat: { // args
      chatId: string; // String!
    }
    deleteFriend: { // args
      friendId: string; // String!
    }
    deleteMessage: { // args
      messageId: string; // String!
    }
    removeMembersFromChat: { // args
      chatId: string; // String!
      membersIds: string[]; // [String!]!
    }
    sendFriendRequest: { // args
      friendId: string; // String!
    }
    updateChat: { // args
      data?: NexusGenInputs['UpdateChatInput'] | null; // UpdateChatInput
    }
    updateMe: { // args
      email: string; // String!
      username: string; // String!
    }
    updateMessage: { // args
      content: string; // String!
      messageId: string; // String!
    }
  }
  Query: {
    chat: { // args
      chatId: string; // String!
    }
    message: { // args
      messageId: string; // String!
    }
    messages: { // args
      after?: string | null; // String
      before?: string | null; // String
      chatId: string; // String!
      first?: number | null; // Int
      last?: number | null; // Int
    }
    user: { // args
      userId: string; // String!
    }
    users: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenInputs['UserOrderBy'] | null; // UserOrderBy
      usernameFilter?: string | null; // String
    }
  }
  Subscription: {
    messageDeleted: { // args
      chatId: string; // String!
    }
    messageUpdated: { // args
      chatId: string; // String!
    }
    messages: { // args
      chatId: string; // String!
    }
  }
  KnownUserInterface: {
    friends: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
}

export interface NexusGenAbstractTypeMembers {
  ChatResult: "DeletedChat" | "DirectMessageChat" | "GroupChat"
  MessageResult: "DeletedMessage" | "Message"
  UserResult: "Friend" | "Me" | "Stranger"
  ChatInterface: "DeletedChat" | "DirectMessageChat" | "GroupChat"
  KnownUserInterface: "Friend" | "Me"
  MessageInterface: "DeletedMessage" | "Message"
  UserInterface: "Friend" | "Me" | "Stranger"
}

export interface NexusGenTypeInterfaces {
  DeletedChat: "ChatInterface"
  DeletedMessage: "MessageInterface"
  DirectMessageChat: "ChatInterface"
  Friend: "KnownUserInterface" | "UserInterface"
  GroupChat: "ChatInterface"
  Me: "KnownUserInterface" | "UserInterface"
  Message: "MessageInterface"
  Stranger: "UserInterface"
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = keyof NexusGenInterfaces;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = keyof NexusGenUnions;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = "ChatInterface" | "ChatResult" | "KnownUserInterface" | "MessageInterface" | "MessageResult" | "UserInterface" | "UserResult";

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: IContext;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
    
    /**
     * Authorization for an individual field. Returning "true"
     * or "Promise<true>" means the field can be accessed.
     * Returning "false" or "Promise<false>" will respond
     * with a "Not Authorized" error for the field.
     * Returning or throwing an error will also prevent the
     * resolver from executing.
     */
    authorize?: FieldAuthorizeResolver<TypeName, FieldName>
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}