/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { IContext } from "./graphql/context.interface"
import type { core, connectionPluginCore } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * Date custom scalar type
     */
    date<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "Date";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * Adds a Relay-style connection to the type, with numerous options for configuration
     *
     * @see https://nexusjs.org/docs/plugins/connection
     */
    connectionField<FieldName extends string>(
      fieldName: FieldName,
      config: connectionPluginCore.ConnectionFieldConfig<TypeName, FieldName>
    ): void
    /**
     * Date custom scalar type
     */
    date<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "Date";
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  UserOrderBy: { // input type
    createdAt?: NexusGenEnums['Sort'] | null; // Sort
    email?: NexusGenEnums['Sort'] | null; // Sort
    id?: NexusGenEnums['Sort'] | null; // Sort
    name?: NexusGenEnums['Sort'] | null; // Sort
    updatedAt?: NexusGenEnums['Sort'] | null; // Sort
    username?: NexusGenEnums['Sort'] | null; // Sort
  }
}

export interface NexusGenEnums {
  FriendStatus: "FRIEND" | "NOT_FRIEND" | "REQUEST_RECEIVED" | "REQUEST_SENT"
  Sort: "asc" | "desc"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  Date: any
}

export interface NexusGenObjects {
  Channel: { // root type
    createdAt: NexusGenScalars['Date']; // Date!
    id: number; // Int!
    isDM: boolean; // Boolean!
    name: string; // String!
    updatedAt: NexusGenScalars['Date']; // Date!
  }
  Message: { // root type
    content: string; // String!
    createdAt: NexusGenScalars['Date']; // Date!
    createdById: number; // Int!
    id: number; // Int!
    updatedAt: NexusGenScalars['Date']; // Date!
  }
  MessageConnection: { // root type
    edges?: Array<NexusGenRootTypes['MessageEdge'] | null> | null; // [MessageEdge]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  MessageEdge: { // root type
    cursor: string; // String!
    node?: NexusGenRootTypes['Message'] | null; // Message
  }
  Mutation: {};
  NewMessagePayload: { // root type
    channelId: number; // Int!
    message: NexusGenRootTypes['Message']; // Message!
  }
  PageInfo: { // root type
    endCursor?: string | null; // String
    hasNextPage: boolean; // Boolean!
    hasPreviousPage: boolean; // Boolean!
    startCursor?: string | null; // String
  }
  Query: {};
  Subscription: {};
  User: { // root type
    createdAt: NexusGenScalars['Date']; // Date!
    email: string; // String!
    id: number; // Int!
    name?: string | null; // String
    updatedAt: NexusGenScalars['Date']; // Date!
    username: string; // String!
  }
  UserConnection: { // root type
    edges?: Array<NexusGenRootTypes['UserEdge'] | null> | null; // [UserEdge]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  UserEdge: { // root type
    cursor: string; // String!
    node?: NexusGenRootTypes['User'] | null; // User
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  Channel: { // field return type
    createdAt: NexusGenScalars['Date']; // Date!
    createdBy: NexusGenRootTypes['User']; // User!
    id: number; // Int!
    isDM: boolean; // Boolean!
    memberCount: number; // Int!
    members: NexusGenRootTypes['User'][]; // [User!]!
    messages: NexusGenRootTypes['MessageConnection']; // MessageConnection!
    name: string; // String!
    updatedAt: NexusGenScalars['Date']; // Date!
  }
  Message: { // field return type
    channel: NexusGenRootTypes['Channel']; // Channel!
    content: string; // String!
    createdAt: NexusGenScalars['Date']; // Date!
    createdBy: NexusGenRootTypes['User']; // User!
    createdById: number; // Int!
    id: number; // Int!
    likedBy: NexusGenRootTypes['User'][]; // [User!]!
    updatedAt: NexusGenScalars['Date']; // Date!
  }
  MessageConnection: { // field return type
    edges: Array<NexusGenRootTypes['MessageEdge'] | null> | null; // [MessageEdge]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  MessageEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['Message'] | null; // Message
  }
  Mutation: { // field return type
    acceptFriendRequest: boolean | null; // Boolean
    addMembersToChannel: NexusGenRootTypes['Channel'] | null; // Channel
    cancelFriendRequest: boolean | null; // Boolean
    createChannel: NexusGenRootTypes['Channel'] | null; // Channel
    createDM: NexusGenRootTypes['Channel'] | null; // Channel
    createMessage: NexusGenRootTypes['Message'] | null; // Message
    declineFriendRequest: boolean | null; // Boolean
    deleteChannel: boolean | null; // Boolean
    deleteFriend: boolean | null; // Boolean
    deleteMessage: NexusGenRootTypes['Message'] | null; // Message
    editMessage: NexusGenRootTypes['Message'] | null; // Message
    removeMembersFromChannel: NexusGenRootTypes['Channel'] | null; // Channel
    sendFriendRequest: boolean | null; // Boolean
    updateChannel: NexusGenRootTypes['Channel'] | null; // Channel
    updateUser: NexusGenRootTypes['User'] | null; // User
  }
  NewMessagePayload: { // field return type
    channelId: number; // Int!
    message: NexusGenRootTypes['Message']; // Message!
  }
  PageInfo: { // field return type
    endCursor: string | null; // String
    hasNextPage: boolean; // Boolean!
    hasPreviousPage: boolean; // Boolean!
    startCursor: string | null; // String
  }
  Query: { // field return type
    channel: NexusGenRootTypes['Channel'] | null; // Channel
    channelMessages: NexusGenRootTypes['MessageConnection']; // MessageConnection!
    channels: NexusGenRootTypes['Channel'][]; // [Channel!]!
    friends: NexusGenRootTypes['User'][]; // [User!]!
    me: NexusGenRootTypes['User'] | null; // User
    user: NexusGenRootTypes['User'] | null; // User
    users: NexusGenRootTypes['UserConnection']; // UserConnection!
  }
  Subscription: { // field return type
    newFriend: NexusGenRootTypes['User'] | null; // User
    newFriendRequest: NexusGenRootTypes['User'] | null; // User
    newMessage: NexusGenRootTypes['NewMessagePayload'] | null; // NewMessagePayload
  }
  User: { // field return type
    channels: NexusGenRootTypes['Channel'][]; // [Channel!]!
    createdAt: NexusGenScalars['Date']; // Date!
    email: string; // String!
    friendStatus: NexusGenEnums['FriendStatus']; // FriendStatus!
    friends: NexusGenRootTypes['UserConnection']; // UserConnection!
    id: number; // Int!
    name: string | null; // String
    receivedFriendRequests: NexusGenRootTypes['User'][]; // [User!]!
    sentFriendRequests: NexusGenRootTypes['User'][]; // [User!]!
    updatedAt: NexusGenScalars['Date']; // Date!
    username: string; // String!
  }
  UserConnection: { // field return type
    edges: Array<NexusGenRootTypes['UserEdge'] | null> | null; // [UserEdge]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  UserEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['User'] | null; // User
  }
}

export interface NexusGenFieldTypeNames {
  Channel: { // field return type name
    createdAt: 'Date'
    createdBy: 'User'
    id: 'Int'
    isDM: 'Boolean'
    memberCount: 'Int'
    members: 'User'
    messages: 'MessageConnection'
    name: 'String'
    updatedAt: 'Date'
  }
  Message: { // field return type name
    channel: 'Channel'
    content: 'String'
    createdAt: 'Date'
    createdBy: 'User'
    createdById: 'Int'
    id: 'Int'
    likedBy: 'User'
    updatedAt: 'Date'
  }
  MessageConnection: { // field return type name
    edges: 'MessageEdge'
    pageInfo: 'PageInfo'
  }
  MessageEdge: { // field return type name
    cursor: 'String'
    node: 'Message'
  }
  Mutation: { // field return type name
    acceptFriendRequest: 'Boolean'
    addMembersToChannel: 'Channel'
    cancelFriendRequest: 'Boolean'
    createChannel: 'Channel'
    createDM: 'Channel'
    createMessage: 'Message'
    declineFriendRequest: 'Boolean'
    deleteChannel: 'Boolean'
    deleteFriend: 'Boolean'
    deleteMessage: 'Message'
    editMessage: 'Message'
    removeMembersFromChannel: 'Channel'
    sendFriendRequest: 'Boolean'
    updateChannel: 'Channel'
    updateUser: 'User'
  }
  NewMessagePayload: { // field return type name
    channelId: 'Int'
    message: 'Message'
  }
  PageInfo: { // field return type name
    endCursor: 'String'
    hasNextPage: 'Boolean'
    hasPreviousPage: 'Boolean'
    startCursor: 'String'
  }
  Query: { // field return type name
    channel: 'Channel'
    channelMessages: 'MessageConnection'
    channels: 'Channel'
    friends: 'User'
    me: 'User'
    user: 'User'
    users: 'UserConnection'
  }
  Subscription: { // field return type name
    newFriend: 'User'
    newFriendRequest: 'User'
    newMessage: 'NewMessagePayload'
  }
  User: { // field return type name
    channels: 'Channel'
    createdAt: 'Date'
    email: 'String'
    friendStatus: 'FriendStatus'
    friends: 'UserConnection'
    id: 'Int'
    name: 'String'
    receivedFriendRequests: 'User'
    sentFriendRequests: 'User'
    updatedAt: 'Date'
    username: 'String'
  }
  UserConnection: { // field return type name
    edges: 'UserEdge'
    pageInfo: 'PageInfo'
  }
  UserEdge: { // field return type name
    cursor: 'String'
    node: 'User'
  }
}

export interface NexusGenArgTypes {
  Channel: {
    messages: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  Mutation: {
    acceptFriendRequest: { // args
      friendId: number; // Int!
    }
    addMembersToChannel: { // args
      channelId: number; // Int!
      memberIds: number[]; // [Int!]!
    }
    cancelFriendRequest: { // args
      friendId: number; // Int!
    }
    createChannel: { // args
      description?: string | null; // String
      isPrivate: boolean | null; // Boolean
      memberIds?: number[] | null; // [Int!]
      name: string; // String!
    }
    createMessage: { // args
      channelId: number; // Int!
      content: string; // String!
    }
    declineFriendRequest: { // args
      friendId: number; // Int!
    }
    deleteChannel: { // args
      channelId: number; // Int!
    }
    deleteFriend: { // args
      friendId: number; // Int!
    }
    deleteMessage: { // args
      messageId: number; // Int!
    }
    editMessage: { // args
      content: string; // String!
      messageId: number; // Int!
    }
    removeMembersFromChannel: { // args
      channelId: number; // Int!
      membersIds: number[]; // [Int!]!
    }
    sendFriendRequest: { // args
      friendId: number; // Int!
    }
    updateChannel: { // args
      channelId: number; // Int!
      isPrivate?: boolean | null; // Boolean
      name?: string | null; // String
    }
    updateUser: { // args
      email: string; // String!
      username: string; // String!
    }
  }
  Query: {
    channel: { // args
      channelId: number; // Int!
    }
    channelMessages: { // args
      after?: string | null; // String
      before?: string | null; // String
      channelId: number; // Int!
      first?: number | null; // Int
      last?: number | null; // Int
    }
    user: { // args
      id: number; // Int!
    }
    users: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenInputs['UserOrderBy'] | null; // UserOrderBy
      usernameFilter?: string | null; // String
    }
  }
  Subscription: {
    newFriend: { // args
      userId: number; // Int!
    }
    newMessage: { // args
      channelId: number; // Int!
    }
  }
  User: {
    friends: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: IContext;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
    
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}